#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HTML = ROOT / "web" / "vrs_desktop.html"
HEADER = ROOT / "generated" / "vrs_web_assets.h"

if not HTML.exists():
    raise SystemExit(f"Missing web page: {HTML}")

data = HTML.read_bytes()

lines = []
for offset in range(0, len(data), 16):
    chunk = data[offset:offset + 16]
    values = ", ".join(f"0x{b:02x}" for b in chunk)
    lines.append(f"    {values},")

content = f"""/* Auto-generated from web/vrs_desktop.html.
 * Do not edit this file directly; edit the HTML source instead.
 */

#ifndef VRS_WEB_ASSETS_H
#define VRS_WEB_ASSETS_H

#include <stddef.h>

static const unsigned char vrs_desktop_html[] = {{
{chr(10).join(lines)}
    0x00
}};

static const size_t vrs_desktop_html_len = sizeof(vrs_desktop_html) - 1;

#endif
"""

HEADER.parent.mkdir(parents=True, exist_ok=True)
HEADER.write_text(content, encoding="utf-8")

print(f"Generated: {HEADER}")
print(f"Embedded HTML bytes: {len(data)}")
